default: ZadanieDomowe1.c
	# gcc ZadanieDomowe1.c -o ZadanieDomowe1
	gcc ZadanieDomowe1_3.c -o ZadanieDomowe1_3
	gcc ZadanieDomowe1_3_rek.c -o ZadanieDomowe1_3_rek
	gcc ZadanieDomoweFork.c -o ZadanieDomoweFork
	gcc Zadanie7Fork.c -o Zadanie7Fork
	gcc Zadanie6Fork.c -o Zadanie6Fork
